version: 2.1

jobs:
  deploy:
    parameters:
      num_retries:
        type: integer
        default: 0
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: (mock) Setup
          command: echo "Here, we install prerequisites, like aws-cli, etc."
      - run:
          name: (mock) Deploy
          command: |
            RETRIES=<< parameters.num_retries >>

            function deploy() {
              RETVAL=$(echo "$RANDOM % 2" | bc)
              echo "Here, we try to deploy/roll out our changes: ${RETVAL}"
              return $RETVAL
            }

            SUCCESS=$(deploy)

            while [ ($SUCCESS -ne 0) && ($RETRIES -gt 0) ]
            do
              sleep 2
              ((RETRIES--))
              SUCCESS=$(deploy)
            done
      - run:
          name: (mock) Post-deploy Cleanup
          command: echo "Here, we run any post-deployment instructions"


workflows:
  main:
    jobs:
      - deploy:
          num_retries: 1
